[package]
name = "layered-lru"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
aptos-drop-helper = { workspace = true }
aptos-experimental-layered-map = { workspace = true }
